### PR TITLE
Optimize CI

### PR DESCRIPTION
**Pull request by vincentmacri**
This PR fixes CI caching once and for all.

---

Blocked by: ~~#29~~
Blocks: none

### CODE REVIEW

**Comment by vincentmacri** [comment]
Woo I fixed caching.

**Comment by vincentmacri** [comment]
Don't merge this until #29 merges, I want to be sure that the cache fails if a dependency is updated, and #29 updates one of the dependencies (http-proxy).

**Comment by tyxchen** [comment]
@vincentmacri just merged #29, want to test the cache out?

**Comment by vincentmacri** [comment]
Looks good. @tyxchen approval to merge?

**Pull request merged**
