### PR TITLE
Allegedly fix hundreds of security vulnerabilities

### PR DESCRIPTION
**Pull request by vincentmacri**
I ran `npm audit fix` a few times.

This PR updates a bunch of packages that npm says have security vulnerabilities.

This PR also adds a CI test for security vulnerabilities with at least a moderate severity level.

### CODE REVIEW

**Comment by vincentmacri** [comment]
I haven't tested if this breaks anything because I need #17 to be merged before I'm able to locally run the project.

**Comment by vincentmacri** [comment]
This PR should *really* be tested by someone who knows this software better than I do before merging.

**Comment by tyxchen** [comment]
This broke express.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:317:13)
    at /home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:335:12)
    at next (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:317:13)
    at /home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:335:12)
    at next (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/home/terry/Documents/Projects/slugline/slugline-web/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by tyxchen** [comment]
I've unbroke express. Should be good now.

**Pull request merged**
